apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner-api
  template:
    metadata:
      labels:
        app: scanner-api
    spec:
      serviceAccountName: scanner-api-sa  # ربطنا الصلاحيات
      containers:
      - name: api
        image: vuln-scanner-api:latest
        imagePullPolicy: Never            # عشان ياخد الصورة اللوكال
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "vuln_scanner"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: scanner-api
spec:
  selector:
    app: scanner-api
  ports:
  - port: 8000
    targetPort: 8000
